=== bimales/projects/xml-validation-dtd/src/main/resources/channel.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT channel (name, topic+)>
<!ELEMENT topic (name, tutorial+)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT tutorial (#PCDATA)>

=== bimales/projects/xml-validation-dtd/src/main/resources/channel.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE channel SYSTEM "src/main/resources/channel.dtd">
<channel>
	<name>ORG.BM Academy</name>
	<topic>
		<name>Design Pattern</name>
		<tutorial>Factory pattern</tutorial>
		<tutorial>Abstract Factory pattern</tutorial>
		<tutorial>Observer pattern</tutorial>
	</topic>
	<topic>
		<name>OOPS Concepts</name>
		<tutorial>Abstraction</tutorial>
		<tutorial>Polymorphism</tutorial>
		<tutorial>Inheritance</tutorial>
	</topic>
</channel>
